#
# SYSTEMD LINKS
#

- name: Create systemd links
  ansible.builtin.file:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    owner: jmorris
    group: jmorris
    state: link
  with_items:
    - { src: '{{ ansible_config_home }}/roles/linux_laptop/files/etc/systemd/logind.conf.{{ inventory_hostname }}', dest: /etc/systemd/logind.conf }
    - { src: '{{ ansible_config_home }}/roles/linux_laptop/files/etc/systemd/sleep.conf.{{ inventory_hostname }}', dest: /etc/systemd/sleep.conf }
    - { 
        src: '{{ ansible_config_home }}/roles/linux_laptop/files/etc/systemd/system/suspend@jmorris.service',
        dest: /etc/systemd/system/suspend@jmorris.service 
      }