---

- name: Load a variable file based on the OS type
  ansible.builtin.include_vars:
    file: '{{ ansible_os_family | lower }}.yaml'

- name: Install common packages on machines with desktop
  become: true
  become_user: jmorris
  ansible.builtin.package:
    name:
      - "{{ linux_google_chrome }}"
      - "{{ linux_terminator }}"
      - "{{ linux_vlc }}"
      - "{{ linux_xfce4_notes_plugin }}"
      - "{{ linux_meld }}"
      - "{{ linux_firefox }}"
      - "{{ linux_flameshot }}"

- name: Install common packages on machines with desktop (AUR packages)
  kewlfft.aur.aur:
    name:
      - "{{ anydesk }}"
  become: true
  become_user: aur_builder

- name: Move mimeapps.list to old file
  ansible.builtin.copy:
    remote_src: true
    src: $HOME/.config/mimeapps.list
    dest: $HOME/.config/mimeapps.list.old
    owner: jmorris
    group: jmorris
    mode: '0644'

- name: Copy mimeapps.list to .config
  ansible.builtin.copy:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    owner: jmorris
    group: jmorris
    mode: '0644'
  with_items:
    - { src: mimeapps.list, dest: $HOME/.config/ }
    - { src: google-chrome-stable.desktop, dest: $HOME/.local/share/applications/}
