---

- name: Load a variable file based on the OS type
  ansible.builtin.include_vars:
    file: '{{ ansible_os_family | lower }}.yaml'

- name: Install common packages on machines with desktop
  become: true
  become_user: root
  ansible.builtin.package:
    name:
      - "{{ linux_desktop_google_chrome }}"
      - "{{ linux_desktop_terminator }}"
      - "{{ linux_desktop_vlc }}"
      - "{{ linux_desktop_xfce4_notes_plugin }}"
      - "{{ linux_desktop_meld }}"
      - "{{ linux_desktop_firefox }}"

- name: Install common packages on machines with desktop (AUR packages)
  kewlfft.aur.aur:
    name:
      - "{{ linux_desktop_anydesk }}"
      - "{{ linux_desktop_flameshot }}"
  become: true
  become_user: aur_builder

- name: Check if mimeapps.list is a file
  ansible.builtin.stat:
    path: $HOME/.config/mimeapps.list
  register: mimeappsfile

- name: Move mimeapps.list to old file
  ansible.builtin.copy:
    remote_src: true
    src: $HOME/.config/mimeapps.list
    dest: $HOME/.config/mimeapps.list.old
    owner: jmorris
    group: jmorris
    mode: '0644'
  when: mimeappsfile.stat.islnk is defined and mimeappsfile.stat.islnk == False

- name: Link mimeapps.list
  ansible.builtin.file:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    owner: jmorris
    group: jmorris
    state: link
  with_items:
    - { src: '{{ ansible_config_home }}/roles/linux_desktop/files/mimeapps.list', dest: $HOME/.config/mimeapps.list }
    - { src: '{{ ansible_config_home }}/roles/linux_desktop/files/google-chrome-stable.desktop', dest: $HOME/.local/share/applications/google-chrome-stable.desktop}
