---

- name: Load a variable file based on the OS type
  ansible.builtin.include_vars:
    file: '{{ ansible_os_family | lower }}.yaml'

- name: Install common packages on non-VM desktops
  become: true
  become_user: root
  ansible.builtin.package:
    name:
      - "{{ linux_headful_spotify }}"
      - "{{ linux_headful_veracrypt }}"
      - "{{ linux_headful_slack }}"
      - "{{ linux_headful_pcmanfm }}"
      - "{{ linux_headful_solaar }}"
      - "{{ linux_headful_vscode }}"
      - "{{ linux_headful_redshift }}"
      - "{{ linux_headful_arandr }}"

- name: Install common packages on workstations, laptops (AUR packages)
  kewlfft.aur.aur:
    name:
      # remmina has issues with wireguard connections and issues with git version
      # disabling for now
      #      - "{{ linux_headful_remmina_git }}"
      - "{{ linux_headful_betterbird }}"
      - "{{ linux_headful_zoom }}"
  become: true
  become_user: aur_builder

- name: Link xprofile and default monitor geometry on julia
  ansible.builtin.file:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    owner: jmorris
    group: jmorris
    state: link
  with_items:
    - { src: '{{ ansible_config_home }}/roles/linux_headful/files/screenlayout/xprofile.{{ inventory_hostname }}', dest: $HOME/.xprofile }
    - { src: '{{ ansible_config_home }}/roles/linux_headful/files/screenlayout/default.sh.{{ inventory_hostname }}', dest: $HOME/.screenlayout/default.sh }
  when: inventory_hostname == 'julia'
