---
all:
  vars:
    ansible_user: "jmorris"
    ansible_become: "yes"
    ansible_become_method: "sudo"
    ansible_config_home: "/home/jmorris/dotfiles/ansible"

linux_servers:
  hosts:
    spike:
      ansible_host: 192.168.1.30

linux_workstations:
  hosts:
    julia:
      ansible_host: 192.168.1.15

linux_laptops:
  hosts:
    lin:
      ansible_host: 192.168.1.34
    chopin:
      ansible_host: 192.168.1.35

linux_desktop_vm:
  hosts:
    vicious:
      ansible_host: 192.168.1.33
#
# windows
#
# NOT CLEAR IF NEEDED AT THIS TIME
# DECIDE WHEN SETTING UP WINDOWS AGAIN
#windows_desktop:
#  hosts:
#    jet:
#      ansible_host: 192.168.1.31
#    faye:
#      ansible_host: 192.168.1.32
#    lin:
#      ansible_host: 192.168.1.34
#    chopin:
#      ansible_host: 192.168.1.35
#
# groups
#

virtualmachines:
  children:
    linux_desktop_vm:

linux_desktops:
  children:
    linux_workstations:
    linux_laptops:
    linux_desktop_vm:
