---
all:
  vars:
    ansible_user: "jmorris"
    ansible_become: "yes"
    ansible_become_method: "sudo"

linux_servers:
  hosts:
    spike:
      ansible_host: localhost

linux_workstations:
  hosts:
    julia:
      ansible_host: 192.168.1.15

linux_laptops:
  hosts:
    lin:
      ansible_host: 192.168.1.42
    chopin:
      ansible_host: 192.168.1.35

linux_desktop_vm:
  hosts:
    vicious:
      ansible_host: 192.168.1.33
#
# windows
#
windows_desktop:
  hosts:
    jet:
      ansible_host: 192.168.1.31
    faye:
      ansible_host: 192.168.1.32
    lin:
      ansible_host: 192.168.1.34
    chopin:
      ansible_host: 192.168.1.35
#
# groups
#

virtualmachines:
  children:
    linux_desktop_vm:

linux_desktops:
  children:
    linux_workstations:
    linux_latops:
    linux_desktop_vm:



