---
#
# linux
#
- name: All linux hosts
  hosts: all
  become: true
  become_user: jmorris
  roles:
    - linux

# any machine with a desktop whether or not physical, so also vms
- name: All linux hosts with general desktops
  hosts: linux_desktops
  become: true
  become_user: jmorris
  roles:
    - linux_desktop

# machines with physical display
- name: All linux headful servers - physical displays
  hosts: linux_workstations, linux_laptops
  become: true
  become_user: jmorris
  roles:
    - linux_headful

- name: All i3 desktops
  hosts: julia, lin
  become: true
  become_user: jmorris
  roles:
    - linux_i3

- name: All linux laptops
  hosts: linux_laptops
  become: true
  become_user: jmorris
  roles:
    - linux_laptop

#
# windows
#
## NOT CLEAR THIS IS NEEDED, WINDOWS MACHINES CAN BE SETUP QUICK AND USUALLY ONLY USE A FEW
#  DIFFERENT PACKAGES
# - name: All windows machines
#   hosts: windows_desktop
#   become: true
#   become_user: jmorris
#   roles:
#     - windows_desktop
