---

- name: Load a variable file based on the OS type
  ansible.builtin.include_vars:
    file: '{{ ansible_os_family | lower }}.yaml'

- name: Link i3 config
  ansible.builtin.file:
    src: '{{ ansible_config_home }}/roles/linux_i3/files/i3/config.{{ inventory_hostname }}'
    dest: $HOME/.config/i3/config
    owner: jmorris
    group: jmorris
    state: link

- name: Link nitrogen config
  ansible.builtin.file:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    owner: jmorris
    group: jmorris
    state: link
  with_items:
    # need this as global variable
    - { src: '{{ ansible_config_home }}/roles/linux_i3/files/nitrogen/bg-saved.cfg.{{ inventory_hostname }}', dest: $HOME/.config/nitrogen/bg-saved.cfg }

- name: Link dunst config
  ansible.builtin.file:
    src: '{{ ansible_config_home }}/roles/linux_i3/files/dunst/dunstrc.{{ inventory_hostname }}'
    dest: $HOME/.config/dunst/dunstrc
    owner: jmorris
    group: jmorris
    state: link

- name: Link polybar files
  ansible.builtin.file:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    owner: jmorris
    group: jmorris
    state: link
  with_items:
    - { src: '{{ ansible_config_home }}/roles/linux_i3/files/polybar/config.ini.{{ inventory_hostname }}', dest: $HOME/.config/polybar/config.ini }
    - { src: '{{ ansible_config_home }}/roles/linux_i3/files/polybar/openweathermap-simple-silverspring.sh', dest: $HOME/.config/polybar/openweathermap-simple-silverspring.sh }
    - { src: '{{ ansible_config_home }}/roles/linux_i3/files/polybar/launch.sh.{{ inventory_hostname }}', dest: $HOME/.config/polybar/launch.sh }
    - { src: '{{ ansible_config_home }}/roles/linux_i3/files/polybar/redshift.sh', dest: $HOME/.config/polybar/redshift.sh }

- name: Create polybar redshift env.sh file
  ansible.builtin.copy:
    dest: $HOME/.config/polybar/env.sh
    content: |
      export REDSHIFT=on
      export REDSHIFT_TEMP=4500


- name: Install rofi
  ansible.builtin.package:
    name:
      - "{{ linux_i3_rofi }}"

- name: Link rofi config
  ansible.builtin.file:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    owner: jmorris
    group: jmorris
    state: link
  with_items:
    - { src: '{{ ansible_config_home }}/roles/linux_i3/files/rofi/launcher/colors.rasi.{{ inventory_hostname }}', dest: $HOME/.config/rofi/launcher/colors.rasi }
    - { src: '{{ ansible_config_home }}/roles/linux_i3/files/rofi/launcher/fonts.rasi', dest: $HOME/.config/rofi/launcher/fonts.rasi }
    - { src: '{{ ansible_config_home }}/roles/linux_i3/files/rofi/launcher/config.rasi', dest: $HOME/.config/rofi/launcher/config.rasi }
    - { src: '{{ ansible_config_home }}/roles/linux_i3/files/rofi/launcher/style-6.rasi', dest: $HOME/.config/rofi/launcher/style-6.rasi }

#
# SYSTEMD LINKS
#

# TODO: Might need to run 'enable' after copying these files
- name: Create systemd links
  become: true
  become_user: root
  ansible.builtin.file:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    owner: jmorris
    group: jmorris
    state: link
  with_items:
    - {
        src: '{{ ansible_config_home }}/roles/linux_i3/files/etc/systemd/system/suspend@jmorris.service.{{ inventory_hostname }}',
        dest: /etc/systemd/system/suspend@jmorris.service
      }

