remmina: remmina
spotify: spotify
veracrypt: veracrypt
slack: slack-desktop
pcmanfm: pcmanfm
zoom: zoom
solaar: solaar
rofi: rofi
vscode: visual-studio-code-bin
redshift: redshift
arandr: arandr
betterbird: betterbird
neovim: neovim
