---
- name: Install packages
  chocolatey.chocolatey.win_chocolatey:
    name: '{{ item.name }}'
    state: '{{ item.state }}'
  with_items:
    - {name: "googlechrome", state: present}
    - {name: "conemu", state: present}
